### ISSUE TITLE
Vue | Service | how to pass data to my vue component

### ISSUE THREAD

**Issue by abelardolg** [deepinder10/socketio-example#17]
Hi there,

From service, how could you pass any data to any Vue component?

Thanks.

**Comment by molinto** [comment]
Same please

**Comment by deepinder10** [comment]
Hi @abelardolg and @molinto , I have part 2 for the Vue article now.
https://deepinder.me/creating-a-real-time-chat-app-with-vue-socket-io-and-nodejs-2
Hope this clears out your issues? Please let me know if you need more assistance.
